/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyRrcaRouteImport } from './routes/why-rrca'
import { Route as WhyPrepareAmericaRouteImport } from './routes/why-prepare-america'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RequestBriefingRouteImport } from './routes/request-briefing'
import { Route as ProofOfConceptRouteImport } from './routes/proof-of-concept'
import { Route as PrepareAmericaRouteImport } from './routes/prepare-america'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as KimosabeRouteImport } from './routes/kimosabe'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as IndustryProblemRouteImport } from './routes/industry-problem'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as FirstCongressRouteImport } from './routes/first-congress'
import { Route as BuddyClaimRouteImport } from './routes/buddy-claim'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as BRouteRouteImport } from './routes/b/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketCredentialRouteImport } from './routes/ticket.$credential'
import { Route as PrepareAmericaConfirmedRouteImport } from './routes/prepare-america.confirmed'
import { Route as InvitationCredentialRouteImport } from './routes/invitation.$credential'
import { Route as InsiderAcceptRouteImport } from './routes/insider.accept'
import { Route as BUnitedStakeholdersRouteImport } from './routes/b/united-stakeholders'
import { Route as BSelfinsurityRouteImport } from './routes/b/selfinsurity'
import { Route as BRrcaRouteImport } from './routes/b/rrca'
import { Route as BMarketApplicationsRouteImport } from './routes/b/market-applications'
import { Route as BKimosabeRouteImport } from './routes/b/kimosabe'
import { Route as BClaimstoreRouteImport } from './routes/b/claimstore'
import { Route as BBuddyClaimRouteImport } from './routes/b/buddy-claim'
import { Route as AuthenticatedRoomRouteImport } from './routes/_authenticated/room'
import { Route as AuthenticatedLedgerRouteImport } from './routes/_authenticated/ledger'
import { Route as AuthenticatedManualIndexRouteImport } from './routes/_authenticated/manual/index'
import { Route as AuthenticatedInsiderIndexRouteImport } from './routes/_authenticated/insider/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedManualPrintRouteImport } from './routes/_authenticated/manual/print'
import { Route as AuthenticatedManualSlugRouteImport } from './routes/_authenticated/manual/$slug'
import { Route as AuthenticatedInsiderReferRouteImport } from './routes/_authenticated/insider/refer'
import { Route as AuthenticatedAppSearchRouteImport } from './routes/_authenticated/app/search'
import { Route as AuthenticatedAppAccountRouteImport } from './routes/_authenticated/app/account'
import { Route as AuthenticatedAdminTourRouteImport } from './routes/_authenticated/admin/tour'
import { Route as AuthenticatedAdminTicketsRouteImport } from './routes/_authenticated/admin/tickets'
import { Route as AuthenticatedAdminSignalsRouteImport } from './routes/_authenticated/admin/signals'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin/roles'
import { Route as AuthenticatedAdminReadsRouteImport } from './routes/_authenticated/admin/reads'
import { Route as AuthenticatedAdminQueueRouteImport } from './routes/_authenticated/admin/queue'
import { Route as AuthenticatedAdminLedgerRouteImport } from './routes/_authenticated/admin/ledger'
import { Route as AuthenticatedAdminLabRouteImport } from './routes/_authenticated/admin/lab'
import { Route as AuthenticatedAdminInviteRouteImport } from './routes/_authenticated/admin/invite'
import { Route as AuthenticatedAdminIntakeRouteImport } from './routes/_authenticated/admin/intake'
import { Route as AuthenticatedAdminInboxRouteImport } from './routes/_authenticated/admin/inbox'
import { Route as AuthenticatedAdminEvidenceRouteImport } from './routes/_authenticated/admin/evidence'
import { Route as AuthenticatedAdminEditsRouteImport } from './routes/_authenticated/admin/edits'
import { Route as AuthenticatedAdminEconomicsRouteImport } from './routes/_authenticated/admin/economics'
import { Route as AuthenticatedAdminDigestRouteImport } from './routes/_authenticated/admin/digest'
import { Route as AuthenticatedAdminBroadcastRouteImport } from './routes/_authenticated/admin/broadcast'
import { Route as AuthenticatedAppTasksIndexRouteImport } from './routes/_authenticated/app/tasks/index'
import { Route as AuthenticatedAdminScreensIndexRouteImport } from './routes/_authenticated/admin/screens/index'
import { Route as AuthenticatedInsiderDossierSlugRouteImport } from './routes/_authenticated/insider/dossier.$slug'
import { Route as AuthenticatedAppTasksTaskIdRouteImport } from './routes/_authenticated/app/tasks/$taskId'
import { Route as AuthenticatedAppRoleRoleKeyRouteImport } from './routes/_authenticated/app/role.$roleKey'

const WhyRrcaRoute = WhyRrcaRouteImport.update({
  id: '/why-rrca',
  path: '/why-rrca',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyPrepareAmericaRoute = WhyPrepareAmericaRouteImport.update({
  id: '/why-prepare-america',
  path: '/why-prepare-america',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestBriefingRoute = RequestBriefingRouteImport.update({
  id: '/request-briefing',
  path: '/request-briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofOfConceptRoute = ProofOfConceptRouteImport.update({
  id: '/proof-of-concept',
  path: '/proof-of-concept',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepareAmericaRoute = PrepareAmericaRouteImport.update({
  id: '/prepare-america',
  path: '/prepare-america',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const KimosabeRoute = KimosabeRouteImport.update({
  id: '/kimosabe',
  path: '/kimosabe',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryProblemRoute = IndustryProblemRouteImport.update({
  id: '/industry-problem',
  path: '/industry-problem',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstCongressRoute = FirstCongressRouteImport.update({
  id: '/first-congress',
  path: '/first-congress',
  getParentRoute: () => rootRouteImport,
} as any)
const BuddyClaimRoute = BuddyClaimRouteImport.update({
  id: '/buddy-claim',
  path: '/buddy-claim',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const BRouteRoute = BRouteRouteImport.update({
  id: '/b',
  path: '/b',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketCredentialRoute = TicketCredentialRouteImport.update({
  id: '/ticket/$credential',
  path: '/ticket/$credential',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepareAmericaConfirmedRoute = PrepareAmericaConfirmedRouteImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => PrepareAmericaRoute,
} as any)
const InvitationCredentialRoute = InvitationCredentialRouteImport.update({
  id: '/invitation/$credential',
  path: '/invitation/$credential',
  getParentRoute: () => rootRouteImport,
} as any)
const InsiderAcceptRoute = InsiderAcceptRouteImport.update({
  id: '/insider/accept',
  path: '/insider/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const BUnitedStakeholdersRoute = BUnitedStakeholdersRouteImport.update({
  id: '/united-stakeholders',
  path: '/united-stakeholders',
  getParentRoute: () => BRouteRoute,
} as any)
const BSelfinsurityRoute = BSelfinsurityRouteImport.update({
  id: '/selfinsurity',
  path: '/selfinsurity',
  getParentRoute: () => BRouteRoute,
} as any)
const BRrcaRoute = BRrcaRouteImport.update({
  id: '/rrca',
  path: '/rrca',
  getParentRoute: () => BRouteRoute,
} as any)
const BMarketApplicationsRoute = BMarketApplicationsRouteImport.update({
  id: '/market-applications',
  path: '/market-applications',
  getParentRoute: () => BRouteRoute,
} as any)
const BKimosabeRoute = BKimosabeRouteImport.update({
  id: '/kimosabe',
  path: '/kimosabe',
  getParentRoute: () => BRouteRoute,
} as any)
const BClaimstoreRoute = BClaimstoreRouteImport.update({
  id: '/claimstore',
  path: '/claimstore',
  getParentRoute: () => BRouteRoute,
} as any)
const BBuddyClaimRoute = BBuddyClaimRouteImport.update({
  id: '/buddy-claim',
  path: '/buddy-claim',
  getParentRoute: () => BRouteRoute,
} as any)
const AuthenticatedRoomRoute = AuthenticatedRoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLedgerRoute = AuthenticatedLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManualIndexRoute =
  AuthenticatedManualIndexRouteImport.update({
    id: '/manual/',
    path: '/manual/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInsiderIndexRoute =
  AuthenticatedInsiderIndexRouteImport.update({
    id: '/insider/',
    path: '/insider/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManualPrintRoute =
  AuthenticatedManualPrintRouteImport.update({
    id: '/manual/print',
    path: '/manual/print',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManualSlugRoute = AuthenticatedManualSlugRouteImport.update({
  id: '/manual/$slug',
  path: '/manual/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsiderReferRoute =
  AuthenticatedInsiderReferRouteImport.update({
    id: '/insider/refer',
    path: '/insider/refer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSearchRoute = AuthenticatedAppSearchRouteImport.update({
  id: '/app/search',
  path: '/app/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAccountRoute = AuthenticatedAppAccountRouteImport.update({
  id: '/app/account',
  path: '/app/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTourRoute = AuthenticatedAdminTourRouteImport.update({
  id: '/admin/tour',
  path: '/admin/tour',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTicketsRoute =
  AuthenticatedAdminTicketsRouteImport.update({
    id: '/admin/tickets',
    path: '/admin/tickets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSignalsRoute =
  AuthenticatedAdminSignalsRouteImport.update({
    id: '/admin/signals',
    path: '/admin/signals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminReadsRoute = AuthenticatedAdminReadsRouteImport.update({
  id: '/admin/reads',
  path: '/admin/reads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminQueueRoute = AuthenticatedAdminQueueRouteImport.update({
  id: '/admin/queue',
  path: '/admin/queue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminLedgerRoute =
  AuthenticatedAdminLedgerRouteImport.update({
    id: '/admin/ledger',
    path: '/admin/ledger',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLabRoute = AuthenticatedAdminLabRouteImport.update({
  id: '/admin/lab',
  path: '/admin/lab',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminInviteRoute =
  AuthenticatedAdminInviteRouteImport.update({
    id: '/admin/invite',
    path: '/admin/invite',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIntakeRoute =
  AuthenticatedAdminIntakeRouteImport.update({
    id: '/admin/intake',
    path: '/admin/intake',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInboxRoute = AuthenticatedAdminInboxRouteImport.update({
  id: '/admin/inbox',
  path: '/admin/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminEvidenceRoute =
  AuthenticatedAdminEvidenceRouteImport.update({
    id: '/admin/evidence',
    path: '/admin/evidence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEditsRoute = AuthenticatedAdminEditsRouteImport.update({
  id: '/admin/edits',
  path: '/admin/edits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminEconomicsRoute =
  AuthenticatedAdminEconomicsRouteImport.update({
    id: '/admin/economics',
    path: '/admin/economics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDigestRoute =
  AuthenticatedAdminDigestRouteImport.update({
    id: '/admin/digest',
    path: '/admin/digest',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBroadcastRoute =
  AuthenticatedAdminBroadcastRouteImport.update({
    id: '/admin/broadcast',
    path: '/admin/broadcast',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppTasksIndexRoute =
  AuthenticatedAppTasksIndexRouteImport.update({
    id: '/app/tasks/',
    path: '/app/tasks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminScreensIndexRoute =
  AuthenticatedAdminScreensIndexRouteImport.update({
    id: '/admin/screens/',
    path: '/admin/screens/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInsiderDossierSlugRoute =
  AuthenticatedInsiderDossierSlugRouteImport.update({
    id: '/insider/dossier/$slug',
    path: '/insider/dossier/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppTasksTaskIdRoute =
  AuthenticatedAppTasksTaskIdRouteImport.update({
    id: '/app/tasks/$taskId',
    path: '/app/tasks/$taskId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRoleRoleKeyRoute =
  AuthenticatedAppRoleRoleKeyRouteImport.update({
    id: '/app/role/$roleKey',
    path: '/app/role/$roleKey',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/b': typeof BRouteRouteWithChildren
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/briefing': typeof BriefingRoute
  '/buddy-claim': typeof BuddyClaimRoute
  '/first-congress': typeof FirstCongressRoute
  '/founder': typeof FounderRoute
  '/industry-problem': typeof IndustryProblemRoute
  '/investors': typeof InvestorsRoute
  '/kimosabe': typeof KimosabeRoute
  '/policy': typeof PolicyRoute
  '/prepare-america': typeof PrepareAmericaRouteWithChildren
  '/proof-of-concept': typeof ProofOfConceptRoute
  '/request-briefing': typeof RequestBriefingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vision': typeof VisionRoute
  '/why-prepare-america': typeof WhyPrepareAmericaRoute
  '/why-rrca': typeof WhyRrcaRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/room': typeof AuthenticatedRoomRoute
  '/b/buddy-claim': typeof BBuddyClaimRoute
  '/b/claimstore': typeof BClaimstoreRoute
  '/b/kimosabe': typeof BKimosabeRoute
  '/b/market-applications': typeof BMarketApplicationsRoute
  '/b/rrca': typeof BRrcaRoute
  '/b/selfinsurity': typeof BSelfinsurityRoute
  '/b/united-stakeholders': typeof BUnitedStakeholdersRoute
  '/insider/accept': typeof InsiderAcceptRoute
  '/invitation/$credential': typeof InvitationCredentialRoute
  '/prepare-america/confirmed': typeof PrepareAmericaConfirmedRoute
  '/ticket/$credential': typeof TicketCredentialRoute
  '/admin/broadcast': typeof AuthenticatedAdminBroadcastRoute
  '/admin/digest': typeof AuthenticatedAdminDigestRoute
  '/admin/economics': typeof AuthenticatedAdminEconomicsRoute
  '/admin/edits': typeof AuthenticatedAdminEditsRoute
  '/admin/evidence': typeof AuthenticatedAdminEvidenceRoute
  '/admin/inbox': typeof AuthenticatedAdminInboxRoute
  '/admin/intake': typeof AuthenticatedAdminIntakeRoute
  '/admin/invite': typeof AuthenticatedAdminInviteRoute
  '/admin/lab': typeof AuthenticatedAdminLabRoute
  '/admin/ledger': typeof AuthenticatedAdminLedgerRoute
  '/admin/queue': typeof AuthenticatedAdminQueueRoute
  '/admin/reads': typeof AuthenticatedAdminReadsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/signals': typeof AuthenticatedAdminSignalsRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/tour': typeof AuthenticatedAdminTourRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/search': typeof AuthenticatedAppSearchRoute
  '/insider/refer': typeof AuthenticatedInsiderReferRoute
  '/manual/$slug': typeof AuthenticatedManualSlugRoute
  '/manual/print': typeof AuthenticatedManualPrintRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/insider/': typeof AuthenticatedInsiderIndexRoute
  '/manual/': typeof AuthenticatedManualIndexRoute
  '/app/role/$roleKey': typeof AuthenticatedAppRoleRoleKeyRoute
  '/app/tasks/$taskId': typeof AuthenticatedAppTasksTaskIdRoute
  '/insider/dossier/$slug': typeof AuthenticatedInsiderDossierSlugRoute
  '/admin/screens/': typeof AuthenticatedAdminScreensIndexRoute
  '/app/tasks/': typeof AuthenticatedAppTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/b': typeof BRouteRouteWithChildren
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/briefing': typeof BriefingRoute
  '/buddy-claim': typeof BuddyClaimRoute
  '/first-congress': typeof FirstCongressRoute
  '/founder': typeof FounderRoute
  '/industry-problem': typeof IndustryProblemRoute
  '/investors': typeof InvestorsRoute
  '/kimosabe': typeof KimosabeRoute
  '/policy': typeof PolicyRoute
  '/prepare-america': typeof PrepareAmericaRouteWithChildren
  '/proof-of-concept': typeof ProofOfConceptRoute
  '/request-briefing': typeof RequestBriefingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vision': typeof VisionRoute
  '/why-prepare-america': typeof WhyPrepareAmericaRoute
  '/why-rrca': typeof WhyRrcaRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/room': typeof AuthenticatedRoomRoute
  '/b/buddy-claim': typeof BBuddyClaimRoute
  '/b/claimstore': typeof BClaimstoreRoute
  '/b/kimosabe': typeof BKimosabeRoute
  '/b/market-applications': typeof BMarketApplicationsRoute
  '/b/rrca': typeof BRrcaRoute
  '/b/selfinsurity': typeof BSelfinsurityRoute
  '/b/united-stakeholders': typeof BUnitedStakeholdersRoute
  '/insider/accept': typeof InsiderAcceptRoute
  '/invitation/$credential': typeof InvitationCredentialRoute
  '/prepare-america/confirmed': typeof PrepareAmericaConfirmedRoute
  '/ticket/$credential': typeof TicketCredentialRoute
  '/admin/broadcast': typeof AuthenticatedAdminBroadcastRoute
  '/admin/digest': typeof AuthenticatedAdminDigestRoute
  '/admin/economics': typeof AuthenticatedAdminEconomicsRoute
  '/admin/edits': typeof AuthenticatedAdminEditsRoute
  '/admin/evidence': typeof AuthenticatedAdminEvidenceRoute
  '/admin/inbox': typeof AuthenticatedAdminInboxRoute
  '/admin/intake': typeof AuthenticatedAdminIntakeRoute
  '/admin/invite': typeof AuthenticatedAdminInviteRoute
  '/admin/lab': typeof AuthenticatedAdminLabRoute
  '/admin/ledger': typeof AuthenticatedAdminLedgerRoute
  '/admin/queue': typeof AuthenticatedAdminQueueRoute
  '/admin/reads': typeof AuthenticatedAdminReadsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/signals': typeof AuthenticatedAdminSignalsRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/tour': typeof AuthenticatedAdminTourRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/search': typeof AuthenticatedAppSearchRoute
  '/insider/refer': typeof AuthenticatedInsiderReferRoute
  '/manual/$slug': typeof AuthenticatedManualSlugRoute
  '/manual/print': typeof AuthenticatedManualPrintRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/insider': typeof AuthenticatedInsiderIndexRoute
  '/manual': typeof AuthenticatedManualIndexRoute
  '/app/role/$roleKey': typeof AuthenticatedAppRoleRoleKeyRoute
  '/app/tasks/$taskId': typeof AuthenticatedAppTasksTaskIdRoute
  '/insider/dossier/$slug': typeof AuthenticatedInsiderDossierSlugRoute
  '/admin/screens': typeof AuthenticatedAdminScreensIndexRoute
  '/app/tasks': typeof AuthenticatedAppTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/b': typeof BRouteRouteWithChildren
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/briefing': typeof BriefingRoute
  '/buddy-claim': typeof BuddyClaimRoute
  '/first-congress': typeof FirstCongressRoute
  '/founder': typeof FounderRoute
  '/industry-problem': typeof IndustryProblemRoute
  '/investors': typeof InvestorsRoute
  '/kimosabe': typeof KimosabeRoute
  '/policy': typeof PolicyRoute
  '/prepare-america': typeof PrepareAmericaRouteWithChildren
  '/proof-of-concept': typeof ProofOfConceptRoute
  '/request-briefing': typeof RequestBriefingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vision': typeof VisionRoute
  '/why-prepare-america': typeof WhyPrepareAmericaRoute
  '/why-rrca': typeof WhyRrcaRoute
  '/_authenticated/ledger': typeof AuthenticatedLedgerRoute
  '/_authenticated/room': typeof AuthenticatedRoomRoute
  '/b/buddy-claim': typeof BBuddyClaimRoute
  '/b/claimstore': typeof BClaimstoreRoute
  '/b/kimosabe': typeof BKimosabeRoute
  '/b/market-applications': typeof BMarketApplicationsRoute
  '/b/rrca': typeof BRrcaRoute
  '/b/selfinsurity': typeof BSelfinsurityRoute
  '/b/united-stakeholders': typeof BUnitedStakeholdersRoute
  '/insider/accept': typeof InsiderAcceptRoute
  '/invitation/$credential': typeof InvitationCredentialRoute
  '/prepare-america/confirmed': typeof PrepareAmericaConfirmedRoute
  '/ticket/$credential': typeof TicketCredentialRoute
  '/_authenticated/admin/broadcast': typeof AuthenticatedAdminBroadcastRoute
  '/_authenticated/admin/digest': typeof AuthenticatedAdminDigestRoute
  '/_authenticated/admin/economics': typeof AuthenticatedAdminEconomicsRoute
  '/_authenticated/admin/edits': typeof AuthenticatedAdminEditsRoute
  '/_authenticated/admin/evidence': typeof AuthenticatedAdminEvidenceRoute
  '/_authenticated/admin/inbox': typeof AuthenticatedAdminInboxRoute
  '/_authenticated/admin/intake': typeof AuthenticatedAdminIntakeRoute
  '/_authenticated/admin/invite': typeof AuthenticatedAdminInviteRoute
  '/_authenticated/admin/lab': typeof AuthenticatedAdminLabRoute
  '/_authenticated/admin/ledger': typeof AuthenticatedAdminLedgerRoute
  '/_authenticated/admin/queue': typeof AuthenticatedAdminQueueRoute
  '/_authenticated/admin/reads': typeof AuthenticatedAdminReadsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/signals': typeof AuthenticatedAdminSignalsRoute
  '/_authenticated/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/_authenticated/admin/tour': typeof AuthenticatedAdminTourRoute
  '/_authenticated/app/account': typeof AuthenticatedAppAccountRoute
  '/_authenticated/app/search': typeof AuthenticatedAppSearchRoute
  '/_authenticated/insider/refer': typeof AuthenticatedInsiderReferRoute
  '/_authenticated/manual/$slug': typeof AuthenticatedManualSlugRoute
  '/_authenticated/manual/print': typeof AuthenticatedManualPrintRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/insider/': typeof AuthenticatedInsiderIndexRoute
  '/_authenticated/manual/': typeof AuthenticatedManualIndexRoute
  '/_authenticated/app/role/$roleKey': typeof AuthenticatedAppRoleRoleKeyRoute
  '/_authenticated/app/tasks/$taskId': typeof AuthenticatedAppTasksTaskIdRoute
  '/_authenticated/insider/dossier/$slug': typeof AuthenticatedInsiderDossierSlugRoute
  '/_authenticated/admin/screens/': typeof AuthenticatedAdminScreensIndexRoute
  '/_authenticated/app/tasks/': typeof AuthenticatedAppTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/b'
    | '/architecture'
    | '/auth'
    | '/briefing'
    | '/buddy-claim'
    | '/first-congress'
    | '/founder'
    | '/industry-problem'
    | '/investors'
    | '/kimosabe'
    | '/policy'
    | '/prepare-america'
    | '/proof-of-concept'
    | '/request-briefing'
    | '/reset-password'
    | '/roles'
    | '/sitemap.xml'
    | '/vision'
    | '/why-prepare-america'
    | '/why-rrca'
    | '/ledger'
    | '/room'
    | '/b/buddy-claim'
    | '/b/claimstore'
    | '/b/kimosabe'
    | '/b/market-applications'
    | '/b/rrca'
    | '/b/selfinsurity'
    | '/b/united-stakeholders'
    | '/insider/accept'
    | '/invitation/$credential'
    | '/prepare-america/confirmed'
    | '/ticket/$credential'
    | '/admin/broadcast'
    | '/admin/digest'
    | '/admin/economics'
    | '/admin/edits'
    | '/admin/evidence'
    | '/admin/inbox'
    | '/admin/intake'
    | '/admin/invite'
    | '/admin/lab'
    | '/admin/ledger'
    | '/admin/queue'
    | '/admin/reads'
    | '/admin/roles'
    | '/admin/signals'
    | '/admin/tickets'
    | '/admin/tour'
    | '/app/account'
    | '/app/search'
    | '/insider/refer'
    | '/manual/$slug'
    | '/manual/print'
    | '/admin/'
    | '/app/'
    | '/insider/'
    | '/manual/'
    | '/app/role/$roleKey'
    | '/app/tasks/$taskId'
    | '/insider/dossier/$slug'
    | '/admin/screens/'
    | '/app/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/b'
    | '/architecture'
    | '/auth'
    | '/briefing'
    | '/buddy-claim'
    | '/first-congress'
    | '/founder'
    | '/industry-problem'
    | '/investors'
    | '/kimosabe'
    | '/policy'
    | '/prepare-america'
    | '/proof-of-concept'
    | '/request-briefing'
    | '/reset-password'
    | '/roles'
    | '/sitemap.xml'
    | '/vision'
    | '/why-prepare-america'
    | '/why-rrca'
    | '/ledger'
    | '/room'
    | '/b/buddy-claim'
    | '/b/claimstore'
    | '/b/kimosabe'
    | '/b/market-applications'
    | '/b/rrca'
    | '/b/selfinsurity'
    | '/b/united-stakeholders'
    | '/insider/accept'
    | '/invitation/$credential'
    | '/prepare-america/confirmed'
    | '/ticket/$credential'
    | '/admin/broadcast'
    | '/admin/digest'
    | '/admin/economics'
    | '/admin/edits'
    | '/admin/evidence'
    | '/admin/inbox'
    | '/admin/intake'
    | '/admin/invite'
    | '/admin/lab'
    | '/admin/ledger'
    | '/admin/queue'
    | '/admin/reads'
    | '/admin/roles'
    | '/admin/signals'
    | '/admin/tickets'
    | '/admin/tour'
    | '/app/account'
    | '/app/search'
    | '/insider/refer'
    | '/manual/$slug'
    | '/manual/print'
    | '/admin'
    | '/app'
    | '/insider'
    | '/manual'
    | '/app/role/$roleKey'
    | '/app/tasks/$taskId'
    | '/insider/dossier/$slug'
    | '/admin/screens'
    | '/app/tasks'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/b'
    | '/architecture'
    | '/auth'
    | '/briefing'
    | '/buddy-claim'
    | '/first-congress'
    | '/founder'
    | '/industry-problem'
    | '/investors'
    | '/kimosabe'
    | '/policy'
    | '/prepare-america'
    | '/proof-of-concept'
    | '/request-briefing'
    | '/reset-password'
    | '/roles'
    | '/sitemap.xml'
    | '/vision'
    | '/why-prepare-america'
    | '/why-rrca'
    | '/_authenticated/ledger'
    | '/_authenticated/room'
    | '/b/buddy-claim'
    | '/b/claimstore'
    | '/b/kimosabe'
    | '/b/market-applications'
    | '/b/rrca'
    | '/b/selfinsurity'
    | '/b/united-stakeholders'
    | '/insider/accept'
    | '/invitation/$credential'
    | '/prepare-america/confirmed'
    | '/ticket/$credential'
    | '/_authenticated/admin/broadcast'
    | '/_authenticated/admin/digest'
    | '/_authenticated/admin/economics'
    | '/_authenticated/admin/edits'
    | '/_authenticated/admin/evidence'
    | '/_authenticated/admin/inbox'
    | '/_authenticated/admin/intake'
    | '/_authenticated/admin/invite'
    | '/_authenticated/admin/lab'
    | '/_authenticated/admin/ledger'
    | '/_authenticated/admin/queue'
    | '/_authenticated/admin/reads'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/signals'
    | '/_authenticated/admin/tickets'
    | '/_authenticated/admin/tour'
    | '/_authenticated/app/account'
    | '/_authenticated/app/search'
    | '/_authenticated/insider/refer'
    | '/_authenticated/manual/$slug'
    | '/_authenticated/manual/print'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/insider/'
    | '/_authenticated/manual/'
    | '/_authenticated/app/role/$roleKey'
    | '/_authenticated/app/tasks/$taskId'
    | '/_authenticated/insider/dossier/$slug'
    | '/_authenticated/admin/screens/'
    | '/_authenticated/app/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BRouteRoute: typeof BRouteRouteWithChildren
  ArchitectureRoute: typeof ArchitectureRoute
  AuthRoute: typeof AuthRoute
  BriefingRoute: typeof BriefingRoute
  BuddyClaimRoute: typeof BuddyClaimRoute
  FirstCongressRoute: typeof FirstCongressRoute
  FounderRoute: typeof FounderRoute
  IndustryProblemRoute: typeof IndustryProblemRoute
  InvestorsRoute: typeof InvestorsRoute
  KimosabeRoute: typeof KimosabeRoute
  PolicyRoute: typeof PolicyRoute
  PrepareAmericaRoute: typeof PrepareAmericaRouteWithChildren
  ProofOfConceptRoute: typeof ProofOfConceptRoute
  RequestBriefingRoute: typeof RequestBriefingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RolesRoute: typeof RolesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VisionRoute: typeof VisionRoute
  WhyPrepareAmericaRoute: typeof WhyPrepareAmericaRoute
  WhyRrcaRoute: typeof WhyRrcaRoute
  InsiderAcceptRoute: typeof InsiderAcceptRoute
  InvitationCredentialRoute: typeof InvitationCredentialRoute
  TicketCredentialRoute: typeof TicketCredentialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-rrca': {
      id: '/why-rrca'
      path: '/why-rrca'
      fullPath: '/why-rrca'
      preLoaderRoute: typeof WhyRrcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-prepare-america': {
      id: '/why-prepare-america'
      path: '/why-prepare-america'
      fullPath: '/why-prepare-america'
      preLoaderRoute: typeof WhyPrepareAmericaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-briefing': {
      id: '/request-briefing'
      path: '/request-briefing'
      fullPath: '/request-briefing'
      preLoaderRoute: typeof RequestBriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof-of-concept': {
      id: '/proof-of-concept'
      path: '/proof-of-concept'
      fullPath: '/proof-of-concept'
      preLoaderRoute: typeof ProofOfConceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prepare-america': {
      id: '/prepare-america'
      path: '/prepare-america'
      fullPath: '/prepare-america'
      preLoaderRoute: typeof PrepareAmericaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kimosabe': {
      id: '/kimosabe'
      path: '/kimosabe'
      fullPath: '/kimosabe'
      preLoaderRoute: typeof KimosabeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-problem': {
      id: '/industry-problem'
      path: '/industry-problem'
      fullPath: '/industry-problem'
      preLoaderRoute: typeof IndustryProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-congress': {
      id: '/first-congress'
      path: '/first-congress'
      fullPath: '/first-congress'
      preLoaderRoute: typeof FirstCongressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buddy-claim': {
      id: '/buddy-claim'
      path: '/buddy-claim'
      fullPath: '/buddy-claim'
      preLoaderRoute: typeof BuddyClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b': {
      id: '/b'
      path: '/b'
      fullPath: '/b'
      preLoaderRoute: typeof BRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$credential': {
      id: '/ticket/$credential'
      path: '/ticket/$credential'
      fullPath: '/ticket/$credential'
      preLoaderRoute: typeof TicketCredentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prepare-america/confirmed': {
      id: '/prepare-america/confirmed'
      path: '/confirmed'
      fullPath: '/prepare-america/confirmed'
      preLoaderRoute: typeof PrepareAmericaConfirmedRouteImport
      parentRoute: typeof PrepareAmericaRoute
    }
    '/invitation/$credential': {
      id: '/invitation/$credential'
      path: '/invitation/$credential'
      fullPath: '/invitation/$credential'
      preLoaderRoute: typeof InvitationCredentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insider/accept': {
      id: '/insider/accept'
      path: '/insider/accept'
      fullPath: '/insider/accept'
      preLoaderRoute: typeof InsiderAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/united-stakeholders': {
      id: '/b/united-stakeholders'
      path: '/united-stakeholders'
      fullPath: '/b/united-stakeholders'
      preLoaderRoute: typeof BUnitedStakeholdersRouteImport
      parentRoute: typeof BRouteRoute
    }
    '/b/selfinsurity': {
      id: '/b/selfinsurity'
      path: '/selfinsurity'
      fullPath: '/b/selfinsurity'
      preLoaderRoute: typeof BSelfinsurityRouteImport
      parentRoute: typeof BRouteRoute
    }
    '/b/rrca': {
      id: '/b/rrca'
      path: '/rrca'
      fullPath: '/b/rrca'
      preLoaderRoute: typeof BRrcaRouteImport
      parentRoute: typeof BRouteRoute
    }
    '/b/market-applications': {
      id: '/b/market-applications'
      path: '/market-applications'
      fullPath: '/b/market-applications'
      preLoaderRoute: typeof BMarketApplicationsRouteImport
      parentRoute: typeof BRouteRoute
    }
    '/b/kimosabe': {
      id: '/b/kimosabe'
      path: '/kimosabe'
      fullPath: '/b/kimosabe'
      preLoaderRoute: typeof BKimosabeRouteImport
      parentRoute: typeof BRouteRoute
    }
    '/b/claimstore': {
      id: '/b/claimstore'
      path: '/claimstore'
      fullPath: '/b/claimstore'
      preLoaderRoute: typeof BClaimstoreRouteImport
      parentRoute: typeof BRouteRoute
    }
    '/b/buddy-claim': {
      id: '/b/buddy-claim'
      path: '/buddy-claim'
      fullPath: '/b/buddy-claim'
      preLoaderRoute: typeof BBuddyClaimRouteImport
      parentRoute: typeof BRouteRoute
    }
    '/_authenticated/room': {
      id: '/_authenticated/room'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof AuthenticatedRoomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ledger': {
      id: '/_authenticated/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AuthenticatedLedgerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manual/': {
      id: '/_authenticated/manual/'
      path: '/manual'
      fullPath: '/manual/'
      preLoaderRoute: typeof AuthenticatedManualIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insider/': {
      id: '/_authenticated/insider/'
      path: '/insider'
      fullPath: '/insider/'
      preLoaderRoute: typeof AuthenticatedInsiderIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manual/print': {
      id: '/_authenticated/manual/print'
      path: '/manual/print'
      fullPath: '/manual/print'
      preLoaderRoute: typeof AuthenticatedManualPrintRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manual/$slug': {
      id: '/_authenticated/manual/$slug'
      path: '/manual/$slug'
      fullPath: '/manual/$slug'
      preLoaderRoute: typeof AuthenticatedManualSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insider/refer': {
      id: '/_authenticated/insider/refer'
      path: '/insider/refer'
      fullPath: '/insider/refer'
      preLoaderRoute: typeof AuthenticatedInsiderReferRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/search': {
      id: '/_authenticated/app/search'
      path: '/app/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AuthenticatedAppSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/account': {
      id: '/_authenticated/app/account'
      path: '/app/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AuthenticatedAppAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tour': {
      id: '/_authenticated/admin/tour'
      path: '/admin/tour'
      fullPath: '/admin/tour'
      preLoaderRoute: typeof AuthenticatedAdminTourRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tickets': {
      id: '/_authenticated/admin/tickets'
      path: '/admin/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/signals': {
      id: '/_authenticated/admin/signals'
      path: '/admin/signals'
      fullPath: '/admin/signals'
      preLoaderRoute: typeof AuthenticatedAdminSignalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reads': {
      id: '/_authenticated/admin/reads'
      path: '/admin/reads'
      fullPath: '/admin/reads'
      preLoaderRoute: typeof AuthenticatedAdminReadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/queue': {
      id: '/_authenticated/admin/queue'
      path: '/admin/queue'
      fullPath: '/admin/queue'
      preLoaderRoute: typeof AuthenticatedAdminQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/ledger': {
      id: '/_authenticated/admin/ledger'
      path: '/admin/ledger'
      fullPath: '/admin/ledger'
      preLoaderRoute: typeof AuthenticatedAdminLedgerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/lab': {
      id: '/_authenticated/admin/lab'
      path: '/admin/lab'
      fullPath: '/admin/lab'
      preLoaderRoute: typeof AuthenticatedAdminLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/invite': {
      id: '/_authenticated/admin/invite'
      path: '/admin/invite'
      fullPath: '/admin/invite'
      preLoaderRoute: typeof AuthenticatedAdminInviteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/intake': {
      id: '/_authenticated/admin/intake'
      path: '/admin/intake'
      fullPath: '/admin/intake'
      preLoaderRoute: typeof AuthenticatedAdminIntakeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/inbox': {
      id: '/_authenticated/admin/inbox'
      path: '/admin/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AuthenticatedAdminInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/evidence': {
      id: '/_authenticated/admin/evidence'
      path: '/admin/evidence'
      fullPath: '/admin/evidence'
      preLoaderRoute: typeof AuthenticatedAdminEvidenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/edits': {
      id: '/_authenticated/admin/edits'
      path: '/admin/edits'
      fullPath: '/admin/edits'
      preLoaderRoute: typeof AuthenticatedAdminEditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/economics': {
      id: '/_authenticated/admin/economics'
      path: '/admin/economics'
      fullPath: '/admin/economics'
      preLoaderRoute: typeof AuthenticatedAdminEconomicsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/digest': {
      id: '/_authenticated/admin/digest'
      path: '/admin/digest'
      fullPath: '/admin/digest'
      preLoaderRoute: typeof AuthenticatedAdminDigestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/broadcast': {
      id: '/_authenticated/admin/broadcast'
      path: '/admin/broadcast'
      fullPath: '/admin/broadcast'
      preLoaderRoute: typeof AuthenticatedAdminBroadcastRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/tasks/': {
      id: '/_authenticated/app/tasks/'
      path: '/app/tasks'
      fullPath: '/app/tasks/'
      preLoaderRoute: typeof AuthenticatedAppTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/screens/': {
      id: '/_authenticated/admin/screens/'
      path: '/admin/screens'
      fullPath: '/admin/screens/'
      preLoaderRoute: typeof AuthenticatedAdminScreensIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insider/dossier/$slug': {
      id: '/_authenticated/insider/dossier/$slug'
      path: '/insider/dossier/$slug'
      fullPath: '/insider/dossier/$slug'
      preLoaderRoute: typeof AuthenticatedInsiderDossierSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/tasks/$taskId': {
      id: '/_authenticated/app/tasks/$taskId'
      path: '/app/tasks/$taskId'
      fullPath: '/app/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedAppTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/role/$roleKey': {
      id: '/_authenticated/app/role/$roleKey'
      path: '/app/role/$roleKey'
      fullPath: '/app/role/$roleKey'
      preLoaderRoute: typeof AuthenticatedAppRoleRoleKeyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLedgerRoute: typeof AuthenticatedLedgerRoute
  AuthenticatedRoomRoute: typeof AuthenticatedRoomRoute
  AuthenticatedAdminBroadcastRoute: typeof AuthenticatedAdminBroadcastRoute
  AuthenticatedAdminDigestRoute: typeof AuthenticatedAdminDigestRoute
  AuthenticatedAdminEconomicsRoute: typeof AuthenticatedAdminEconomicsRoute
  AuthenticatedAdminEditsRoute: typeof AuthenticatedAdminEditsRoute
  AuthenticatedAdminEvidenceRoute: typeof AuthenticatedAdminEvidenceRoute
  AuthenticatedAdminInboxRoute: typeof AuthenticatedAdminInboxRoute
  AuthenticatedAdminIntakeRoute: typeof AuthenticatedAdminIntakeRoute
  AuthenticatedAdminInviteRoute: typeof AuthenticatedAdminInviteRoute
  AuthenticatedAdminLabRoute: typeof AuthenticatedAdminLabRoute
  AuthenticatedAdminLedgerRoute: typeof AuthenticatedAdminLedgerRoute
  AuthenticatedAdminQueueRoute: typeof AuthenticatedAdminQueueRoute
  AuthenticatedAdminReadsRoute: typeof AuthenticatedAdminReadsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminSignalsRoute: typeof AuthenticatedAdminSignalsRoute
  AuthenticatedAdminTicketsRoute: typeof AuthenticatedAdminTicketsRoute
  AuthenticatedAdminTourRoute: typeof AuthenticatedAdminTourRoute
  AuthenticatedAppAccountRoute: typeof AuthenticatedAppAccountRoute
  AuthenticatedAppSearchRoute: typeof AuthenticatedAppSearchRoute
  AuthenticatedInsiderReferRoute: typeof AuthenticatedInsiderReferRoute
  AuthenticatedManualSlugRoute: typeof AuthenticatedManualSlugRoute
  AuthenticatedManualPrintRoute: typeof AuthenticatedManualPrintRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedInsiderIndexRoute: typeof AuthenticatedInsiderIndexRoute
  AuthenticatedManualIndexRoute: typeof AuthenticatedManualIndexRoute
  AuthenticatedAppRoleRoleKeyRoute: typeof AuthenticatedAppRoleRoleKeyRoute
  AuthenticatedAppTasksTaskIdRoute: typeof AuthenticatedAppTasksTaskIdRoute
  AuthenticatedInsiderDossierSlugRoute: typeof AuthenticatedInsiderDossierSlugRoute
  AuthenticatedAdminScreensIndexRoute: typeof AuthenticatedAdminScreensIndexRoute
  AuthenticatedAppTasksIndexRoute: typeof AuthenticatedAppTasksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLedgerRoute: AuthenticatedLedgerRoute,
  AuthenticatedRoomRoute: AuthenticatedRoomRoute,
  AuthenticatedAdminBroadcastRoute: AuthenticatedAdminBroadcastRoute,
  AuthenticatedAdminDigestRoute: AuthenticatedAdminDigestRoute,
  AuthenticatedAdminEconomicsRoute: AuthenticatedAdminEconomicsRoute,
  AuthenticatedAdminEditsRoute: AuthenticatedAdminEditsRoute,
  AuthenticatedAdminEvidenceRoute: AuthenticatedAdminEvidenceRoute,
  AuthenticatedAdminInboxRoute: AuthenticatedAdminInboxRoute,
  AuthenticatedAdminIntakeRoute: AuthenticatedAdminIntakeRoute,
  AuthenticatedAdminInviteRoute: AuthenticatedAdminInviteRoute,
  AuthenticatedAdminLabRoute: AuthenticatedAdminLabRoute,
  AuthenticatedAdminLedgerRoute: AuthenticatedAdminLedgerRoute,
  AuthenticatedAdminQueueRoute: AuthenticatedAdminQueueRoute,
  AuthenticatedAdminReadsRoute: AuthenticatedAdminReadsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminSignalsRoute: AuthenticatedAdminSignalsRoute,
  AuthenticatedAdminTicketsRoute: AuthenticatedAdminTicketsRoute,
  AuthenticatedAdminTourRoute: AuthenticatedAdminTourRoute,
  AuthenticatedAppAccountRoute: AuthenticatedAppAccountRoute,
  AuthenticatedAppSearchRoute: AuthenticatedAppSearchRoute,
  AuthenticatedInsiderReferRoute: AuthenticatedInsiderReferRoute,
  AuthenticatedManualSlugRoute: AuthenticatedManualSlugRoute,
  AuthenticatedManualPrintRoute: AuthenticatedManualPrintRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedInsiderIndexRoute: AuthenticatedInsiderIndexRoute,
  AuthenticatedManualIndexRoute: AuthenticatedManualIndexRoute,
  AuthenticatedAppRoleRoleKeyRoute: AuthenticatedAppRoleRoleKeyRoute,
  AuthenticatedAppTasksTaskIdRoute: AuthenticatedAppTasksTaskIdRoute,
  AuthenticatedInsiderDossierSlugRoute: AuthenticatedInsiderDossierSlugRoute,
  AuthenticatedAdminScreensIndexRoute: AuthenticatedAdminScreensIndexRoute,
  AuthenticatedAppTasksIndexRoute: AuthenticatedAppTasksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BRouteRouteChildren {
  BBuddyClaimRoute: typeof BBuddyClaimRoute
  BClaimstoreRoute: typeof BClaimstoreRoute
  BKimosabeRoute: typeof BKimosabeRoute
  BMarketApplicationsRoute: typeof BMarketApplicationsRoute
  BRrcaRoute: typeof BRrcaRoute
  BSelfinsurityRoute: typeof BSelfinsurityRoute
  BUnitedStakeholdersRoute: typeof BUnitedStakeholdersRoute
}

const BRouteRouteChildren: BRouteRouteChildren = {
  BBuddyClaimRoute: BBuddyClaimRoute,
  BClaimstoreRoute: BClaimstoreRoute,
  BKimosabeRoute: BKimosabeRoute,
  BMarketApplicationsRoute: BMarketApplicationsRoute,
  BRrcaRoute: BRrcaRoute,
  BSelfinsurityRoute: BSelfinsurityRoute,
  BUnitedStakeholdersRoute: BUnitedStakeholdersRoute,
}

const BRouteRouteWithChildren =
  BRouteRoute._addFileChildren(BRouteRouteChildren)

interface PrepareAmericaRouteChildren {
  PrepareAmericaConfirmedRoute: typeof PrepareAmericaConfirmedRoute
}

const PrepareAmericaRouteChildren: PrepareAmericaRouteChildren = {
  PrepareAmericaConfirmedRoute: PrepareAmericaConfirmedRoute,
}

const PrepareAmericaRouteWithChildren = PrepareAmericaRoute._addFileChildren(
  PrepareAmericaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BRouteRoute: BRouteRouteWithChildren,
  ArchitectureRoute: ArchitectureRoute,
  AuthRoute: AuthRoute,
  BriefingRoute: BriefingRoute,
  BuddyClaimRoute: BuddyClaimRoute,
  FirstCongressRoute: FirstCongressRoute,
  FounderRoute: FounderRoute,
  IndustryProblemRoute: IndustryProblemRoute,
  InvestorsRoute: InvestorsRoute,
  KimosabeRoute: KimosabeRoute,
  PolicyRoute: PolicyRoute,
  PrepareAmericaRoute: PrepareAmericaRouteWithChildren,
  ProofOfConceptRoute: ProofOfConceptRoute,
  RequestBriefingRoute: RequestBriefingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RolesRoute: RolesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VisionRoute: VisionRoute,
  WhyPrepareAmericaRoute: WhyPrepareAmericaRoute,
  WhyRrcaRoute: WhyRrcaRoute,
  InsiderAcceptRoute: InsiderAcceptRoute,
  InvitationCredentialRoute: InvitationCredentialRoute,
  TicketCredentialRoute: TicketCredentialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
